apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-config
  namespace: demo-k8s
data:
  MONGO_INITDB_DATABASE: user

---

apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: demo-k8s
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cm9vdA==