apiVersion: v1
kind: ConfigMap
metadata:
  name: post-srv-config
  namespace: demo-k8s
data:
  AUTH_DB_NAME: admin
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_NAME: post
  DB_PORT: "27017"
  DB_HOST: post-db-service
  USER_API_URL: http://user-srv-service:8080