apiVersion: v1
kind: Service
metadata:
  name: post-db-service
  namespace: {{ .Values.namespace }}
  labels:
    app: post-db
spec:
  selector:
    app: post-db
  ports:
  - port: 27017
    targetPort: 27017