apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: {{ .Values.namespace }}
  labels:
    app: user-db
spec:
  selector:
    app: user-db
  ports:
  - port: 27017
    targetPort: 27017