apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-config
  namespace: {{ .Values.namespace }}
  {{- template "metadata.labels" }}
data:
  MONGO_INITDB_DATABASE: user

---

apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: {{ .Values.namespace }}
  {{- template "metadata.labels" }}
type: Opaque
data:
  {{- range $key, $val := .Values.db.secrets }}
    {{ $key }}: {{ $val }}
  {{- end }}
