apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: demo-k8s
  labels:
    app: user-db
spec:
  selector:
    matchLabels:
      app: user-db
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-mongo-container
          image: mongo:latest
          envFrom:
            - configMapRef:
                name: user-db-config
            - secretRef:
                name: user-db-secret