apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: post-db-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: post-db-sc
  local:
    path: /host/post-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo-k8s
  name: post-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: post-db-sc
  resources:
    requests:
      storage: 1Gi
