apiVersion: v1
kind: ConfigMap
metadata:
  name: user-srv-config
  namespace: demo-k8s
data:
  AUTH_DB_NAME: admin
  DB_NAME: user
  DB_PORT: "27017"
  DB_HOST: user-db-service
  POST_API_URL: http://post-srv-service:8080

---

apiVersion: v1
kind: Secret
metadata:
  name: user-srv-secret
  namespace: demo-k8s
type: Opaque
data:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: cm9vdA==
